### ISSUE TITLE
pokemon missing?

### ISSUE THREAD

**Issue by myrrien** [GiacomoLaw/pokefinder#13]
I can't find many pokemon, is the site a wip or simply missing things?

**Comment by GiacomoLaw** [comment]
Which Pokemon are missing?

**Comment by myrrien** [comment]
Gastly, drifloon, mudbray.... All the ones which are in a route with a name and not a number seems like.

**Comment by GiacomoLaw** [comment]
Fixed here: https://github.com/GiacomoLaw/pokefinder/pull/16

Thanks for using Pokefinder!

**Comment by myrrien** [comment]
Thanks! I'm checking off the list and it seems like some of the island scans pokemon are still missing

**Comment by GiacomoLaw** [comment]
Do you know which ones? I thought I added all of them. Sorry!

**Comment by myrrien** [comment]
from a quick search: totodile deino horsea klink litwick swinub rosela axew
rhyhorn honedge marill conkeldurr togekiss leavanny serperior samurott
emboar eelektross

**Comment by GiacomoLaw** [comment]
Okay, thanks, I'll get to adding them soon
